# Generated by Django 5.1.7 on 2025-05-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('poblacion', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
